name: Docker Publish to GHCR

on:
  push:
    branches:
      - main # Or your default branch

env:
  IMAGE_NAME: ${{ github.repository_owner }}/grpc-reverse-proxy # Will be <your-username-or-org>/grpc-reverse-proxy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        # This step allows building images for different architectures

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Buildx is a Docker CLI plugin that extends the docker build command
        # with the full support of the features provided by Moby BuildKit builder toolkit.
        # It enables multi-platform builds.

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_TOKEN is automatically created by Actions,
          # you don't need to create it manually.

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64 # Target platforms
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
